apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: example
spec:
  minReplicas: 4
  maxReplicas: 15
  behavior:
    scaleDown:
      policies:
      - periodSeconds: 60
        type: Pods
        value: 1
      selectPolicy: Max
      stabilizationWindowSeconds: 180
    scaleUp:
      policies:
      - periodSeconds: 30
        type: Pods
        value: 1
      selectPolicy: Max
      stabilizationWindowSeconds: 30
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: example
  metrics:
    - resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
      type: Resource
    - type: Resource
      resource:
        name: memory
        target:
          averageUtilization: 80
          type: Utilization
